Common build system for McStas and McXtrace. May be used from SVN trunk (e.g. configure --enable-mcstas) or from mkdist.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,5 +1,5 @@
 #
-#   This file is part of the @PACKAGE_STRING@ neutron ray-trace simulation package
+#   This file is part of the McStas/McXtrace @PACKAGE_STRING@ neutron ray-trace simulation package
 #   Copyright (C) 1997-2010, All rights reserved
 #   Risoe National Laborartory, Roskilde, Denmark
 #   Institut Laue Langevin, Grenoble, France
@@ -37,6 +37,60 @@ if test x"$with_cc" != x"no" ; then
 else
         AC_MSG_ERROR([You need a C compiler to compile this package])
 fi
+
+# Have the user select wich version they want to build.
+AC_ARG_ENABLE([mcstas], AC_HELP_STRING([--enable-mcstas], [Enable building McStas binaries.]))
+AC_ARG_ENABLE([mcxtrace], AC_HELP_STRING([--enable-mcxtrace], [Enable building McXtrace binaries.]))
+
+# check if VERSION is defined (in principle, done in mkdist)
+if test x"$PACKAGE_VERSION" == "x@PACKAGE_VERSION@" ; then
+  MONTH=`date +"%b"`
+  DAY=`date +"%d"`
+  YEAR=`date +"%Y"`
+  PACKAGE_DATE="'$MONTH'. '$DAY', '$YEAR'"
+  PACKAGE_VERSION="'$MONTH-$DAY-$YEAR'"
+  for file in src/mccode.h src/mcformat.c doc/man/*.1 support/deb/debcreate support/deb/control support/Win32/install/mcstas.nsi build.bat lib/share/mccode-r.h configure.in;
+  do
+    sed 's/@MCCODE_VERSION@/'$PACKAGE_NAME'-'$PACKAGE_VERSION' - '$MONTH'. '$DAY', '$YEAR'/' $file > $file.tmp
+    sed 's/@PACKAGE_DATE@/'$MONTH'. '$DAY', '$YEAR'/' $file.tmp > $file
+    sed 's/@PACKAGE_TARNAME@/'$PACKAGE_TARNAME'/' $file > $file.tmp
+    sed 's/@PACKAGE_NAME@/'$PACKAGE_NAME'/' $file.tmp > $file
+    sed 's/@PACKAGE_VERSION@/'$PACKAGE_VERSION'/' $file > $file.tmp
+    sed 's/@PACKAGE_STRING@/'$PACKAGE_NAME'-'$PACKAGE_VERSION'/' $file.tmp > $file
+    sed 's/@PACKAGE_TARNAME@/'$PACKAGE_TARNAME'/' $file > $file.tmp
+    mv $file.tmp $file
+  done
+fi
+
+# optional target change (mcstas -> mcxtrace or vice versa)
+if test x"$enable_mcstas" == "xyes" -a x"$enable_mcxtrace" == "xyes" ; then
+  echo "ERROR: It is currently not possible to build both mcstas and mcxtrace."
+  exit 1
+elif test x"$enable_mcstas" == "xyes" ; then
+  PACKAGE_TARNAME=[mcstas]
+  PACKAGE_NAME=McStas
+  PACKAGE_STRING="$PACKAGE_NAME $PACKAGE_VERSION"
+  if [[ -e lib/tools/perl/mcxtrace_config.perl.in ]]; then
+    mv lib/tools/perl/mcxtrace_config.perl.in lib/tools/perl/mccode_config.perl.in
+  fi
+  if [[ -e lib/tools/perl/mcxtrace_reconfigure.in ]]; then
+    mv lib/tools/perl/mcxtrace_reconfigure.in lib/tools/perl/mccode_reconfigure.in
+  fi
+elif test x"$enable_mcxtrace" == "xyes" ; then
+  PACKAGE_TARNAME=[mcxtrace]
+  PACKAGE_NAME=McXtrace
+  PACKAGE_STRING="$PACKAGE_NAME $PACKAGE_VERSION"
+  if [[ -e lib/tools/perl/mcstas_config.perl.in ]]; then
+    mv lib/tools/perl/mcstas_config.perl.in lib/tools/perl/mccode_config.perl.in
+  fi
+  if [[ -e lib/tools/perl/mcxtrace_reconfigure.in ]]; then
+    mv lib/tools/perl/mcxtrace_reconfigure.in lib/tools/perl/mccode_reconfigure.in
+  fi
+fi
+AC_SUBST([PACKAGE_TARNAME])
+AC_SUBST([PACKAGE_NAME])
+AC_SUBST([PACKAGE_STRING])
+AC_SUBST([PACKAGE_VERSION])
 
 AC_PROG_INSTALL
 CF_ANSI_CC_CHECK
@@ -101,26 +155,34 @@ else
   AC_DEFINE([HAVE_NEXUS], [])
 fi
 
-AC_OUTPUT(Makefile src/Makefile src/port.h lib/Makefile nlib/Makefile xlib/Makefile lib/tools/perl/@PACKAGE_TARNAME@_config.perl lib/tools/perl/@PACKAGE_TARNAME@_reconfigure support/common/Makefile support/common/pgplot/Makefile support/common/pgplot/makehtml support/common/pgplot/maketex)
+# make sure the target config file and reconfigure scripts are named properly
+if [[ -e lib/tools/perl/mccode_config.perl.in ]]; then
+  mv lib/tools/perl/mccode_config.perl.in lib/tools/perl/${PACKAGE_TARNAME}_config.perl.in
+fi
+if [[ -e lib/tools/perl/mccode_reconfigure.in ]]; then
+  mv lib/tools/perl/mccode_reconfigure.in lib/tools/perl/${PACKAGE_TARNAME}_reconfigure.in
+fi
 
-chmod a+x lib/tools/perl/@PACKAGE_TARNAME@_reconfigure
+AC_OUTPUT(Makefile src/Makefile src/port.h lib/Makefile nlib/Makefile xlib/Makefile lib/tools/perl/${PACKAGE_TARNAME}_config.perl lib/tools/perl/${PACKAGE_TARNAME}_reconfigure support/common/Makefile support/common/pgplot/Makefile support/common/pgplot/makehtml support/common/pgplot/maketex)
+
+chmod a+x lib/tools/perl/${PACKAGE_TARNAME}_reconfigure
 
 # warnings and errors
 if test "$USE_PIC" != "no" ; then
 echo "Activating PIC compilation for: make install-pgplot"
 fi
 if test "x$HAVE_NEXUS" != "x" ; then
-echo "Activating NeXus support in @PACKAGE_STRING@ ($HAVE_NEXUS)"
+echo "Activating NeXus support in $PACKAGE_STRING ($HAVE_NEXUS)"
 fi
 if test "$MAKE" == "no" ; then
-  echo "ERROR: @PACKAGE_STRING@ installation requires 'make' or 'gmake'"
+  echo "ERROR: $PACKAGE_STRING installation requires 'make' or 'gmake'"
   exit
 fi
 
 if test "$PERL" = "no" ; then
   echo "WARNING: No Perl executable could be found !"
   echo "The commands mcrun and mcgui won't be available. You will have to use:"
-  echo "   @PACKAGE_TARNAME@ <file>.instr"
+  echo "   $PACKAGE_TARNAME <file>.instr"
   echo "   $CC -o <file>.out <file>.instr -lm"
   echo "   <file>.out [simulation parameters]"
 fi
@@ -137,14 +199,8 @@ fi
 
 # final message at end of configure
 echo ""
-if test "$WGET" != no ; then
-  echo "Gnome support: If you experience crashes of mcgui when running in the "
-  echo "  Gnome environment, please come back here and do a"
-  echo "# make install-tk"
-  echo "will install our patched version of perl-tk from the net"
-fi
 if test "$PGPLOT" == "no" ; then
-  echo "To install PGPLOT for @PACKAGE_STRING@, you need:"
+  echo "To install PGPLOT for $PACKAGE_STRING, you need:"
   echo "= perl-PDL (perldl, pdl)"
   echo "= a fortran compiler (g77, gfortran)"
   echo "= X11-dev libraries/includes (libx11-dev, xserver-xorg-dev, libxt-dev)"
@@ -155,7 +211,7 @@ if test "$PGPLOT" == "no" && test "$PERLDL" != "no" && test "$G77" != "no" ; the
   echo "# make reconfigure"
   echo "(For 64-bit machines, reconfigure first: # ./configure --with-pic )"
 else if test "$PGPLOT" == "no" ; then
-  echo "To use PGPLOT, install these packages and re-run @PACKAGE_STRING@ installation ./configure"
+  echo "To use PGPLOT, install these packages and re-run $PACKAGE_STRING installation ./configure"
   fi
 fi
 if test "$SCILAB" == "no" && test "$WGET" != no ; then
@@ -182,9 +238,9 @@ if test "$VRMLVIEW" != "no" ; then
 echo "# make vrml   (selects vrml)"
 fi
 echo ""
-echo "After (optional) plotter config, build and install @PACKAGE_STRING@ by executing"
+echo "After (optional) plotter config, build and install $PACKAGE_STRING by executing"
 echo "# make; make install"
-echo "will install @PACKAGE_STRING@ into $prefix"
+echo "will install $PACKAGE_STRING into $prefix"
 echo ""
 if test "$DASH" != "no" ; then
 echo
