Let mcdoc use the new bash header system

diff --git a/tools/Python/mcdoc/mcdoc.in b/tools/Python/mcdoc/mcdoc.in
--- a/tools/Python/mcdoc/mcdoc.in
+++ b/tools/Python/mcdoc/mcdoc.in
@@ -1,35 +1,36 @@
 #!/usr/bin/env bash
 # Wrapper script for @P@doc-py
 
-# First ensure that we follow symlink if needed
-LINK=`readlink $0`
+@MCCODE_BASH_STANDARD_PREAMBLE@
 
-# Am I a symlink?
-if [ "x$LINK" != "x" ]; then
-    LIB=`dirname $LINK`
-else
-    LIB=`dirname $0`
-fi
-if [ -d "$LIB/../miniconda3" ]; then
-    source $LIB/../miniconda3/bin/activate base
-fi
-LIB="$LIB/../tools/Python/@P@doc/"
 TOOL="@P@doc"
-VERS="@MCCODE_VERSION@"
+UTILDIR="${MCCODE_TOOLDIR}/Python/$TOOL"
+
+
+#NB: miniconda should be installed next to the tool folder:
+if [ -d "${MCCODE_TOOLDIR}/../miniconda3" ]; then
+    source "${MCCODE_TOOLDIR}/../miniconda3/bin/activate" base
+fi
+
+# FIXME: NCrystal should be used via own package/infrastructure
+if [ [ @NCRYSTAL_LEGACY_USE@ == 1 ] && -d "${MCCODE_TOOLDIR}/../share/NCrystal/python" ]; then
+    export PYTHONPATH="${MCCODE_TOOLDIR}/../share/NCrystal/python:$PYTHONPATH"
+fi
+
+ARCH=`arch`
+UNAME=`uname -s`
+
+#VERS="@MCCODE_VERSION@"
+
 
 canrun() {
-    if ! [ -x ${LIB}/mcdoc.py ]; then
+    if ! [ -x ${UTILDIR}/mcdoc.py ]; then
         exit 127;
     fi
 }
 
 if ( canrun ); then
-    python3 ${LIB}/mcdoc.py $*
+    python3 -u ${UTILDIR}/mcdoc.py "$@"
 else
-    echo ":: Failed to run Python  ${TOOL}, trying Perl ${TOOL} instead."
-    echo ":: If this fails too, consider reinstalling ${TOOL}."
-    echo ""
-
-    # Try old Perl-version of mcdoc if Python version cannot run
-    ${TOOL} $*
+    echo ":: Failed to run Python  ${TOOL}."
 fi
